/* phxrpc_search_tool.h

 Generated by phxrpc_pb2tool from search.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#pragma once


namespace phxrpc {


class OptMap;


}


class SearchTool {
  public:
    SearchTool();
    virtual ~SearchTool();

    virtual int PHXEcho(phxrpc::OptMap &bigmap);
    virtual int Search(phxrpc::OptMap &bigmap);
    virtual int Notify(phxrpc::OptMap &bigmap);

    typedef int (SearchTool::*ToolFunc_t)(phxrpc::OptMap &);

    typedef struct tagName2Func {
        const char *name;
        SearchTool::ToolFunc_t func;
        const char *opt_string;
        const char *usage;
    } Name2Func_t;

    static Name2Func_t *GetName2Func() {
        static Name2Func_t name2func[]{
            {"PHXEcho", &SearchTool::PHXEcho, "c:f:vs:",
                    "-s <string>"},
            {"Search", &SearchTool::Search, "c:f:vq:",
                    "-q <query>"},
            {"Notify", &SearchTool::Notify, "c:f:vm:",
                    "-m <msg>"},
            {nullptr, nullptr}
        };

        return name2func;
    };
};

