/* phxrpc_search_service.cpp

 Generated by phxrpc_pb2service from search.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#include "phxrpc_search_service.h"

#include "search.pb.h"
#include "phxrpc/file.h"


SearchService::SearchService() {
}

SearchService::~SearchService() {
}

int SearchService::PHXEcho(const google::protobuf::StringValue &/* req */, google::protobuf::StringValue */* resp */) {
    phxrpc::log(LOG_ERR, "ERROR: PHXEcho unimplemented");
    return -1;
}

int SearchService::Search(const search::SearchRequest &/* req */, search::SearchResult */* resp */) {
    phxrpc::log(LOG_ERR, "ERROR: Search unimplemented");
    return -1;
}

int SearchService::Notify(const google::protobuf::StringValue &/* req */, google::protobuf::Empty */* resp */) {
    phxrpc::log(LOG_ERR, "ERROR: Notify unimplemented");
    return -1;
}

