/* phxrpc_search_tool.cpp

 Generated by phxrpc_pb2tool from search.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#include "phxrpc_search_tool.h"

#include "phxrpc/file.h"

#include "search_client.h"


using namespace phxrpc;


SearchTool::SearchTool() {
}

SearchTool::~SearchTool() {
}

int SearchTool::PHXEcho(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** PHXEcho unimplement ***\n");

    return -1;
}

int SearchTool::Search(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** Search unimplement ***\n");

    return -1;
}

int SearchTool::Notify(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** Notify unimplement ***\n");

    return -1;
}

