/* phxrpc_search_stub.h

 Generated by phxrpc_pb2client from search.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#pragma once

#include "search.pb.h"


namespace phxrpc {


class BaseMessageHandlerFactory;
class BaseTcpStream;
class ClientMonitor;


}


class SearchStub {
  public:
    SearchStub(phxrpc::BaseTcpStream &socket, phxrpc::ClientMonitor &client_monitor,
            phxrpc::BaseMessageHandlerFactory &msg_handler_factory);
    virtual ~SearchStub();

    void set_keep_alive(const bool keep_alive);

    int PHXEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp);
    int Search(const search::SearchRequest &req, search::SearchResult *resp);
    int Notify(const google::protobuf::StringValue &req, google::protobuf::Empty *resp);

  private:
    phxrpc::BaseTcpStream &socket_;
    phxrpc::ClientMonitor &client_monitor_;
    bool keep_alive_{false};
    phxrpc::BaseMessageHandlerFactory &msg_handler_factory_;
};

