/* phxrpc_search_dispatcher.h

 Generated by phxrpc_pb2service from search.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#pragma once

#include "phxrpc/rpc.h"


class SearchService;

class SearchDispatcher {
  public:
    static const phxrpc::BaseDispatcher<SearchDispatcher>::URIFuncMap &GetURIFuncMap();

    SearchDispatcher(SearchService &service, phxrpc::DispatcherArgs_t *dispatcher_args);

    virtual ~SearchDispatcher();

    int PHXEcho(const phxrpc::BaseRequest &req, phxrpc::BaseResponse *const resp);
    int Search(const phxrpc::BaseRequest &req, phxrpc::BaseResponse *const resp);
    int Notify(const phxrpc::BaseRequest &req, phxrpc::BaseResponse *const resp);

  private:
    SearchService &service_;
    phxrpc::DispatcherArgs_t *dispatcher_args_;
};

