/* phxrpc_search_stub.cpp

 Generated by phxrpc_pb2client from search.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#include "phxrpc_search_stub.h"

#include "phxrpc/http.h"
#include "phxrpc/network.h"
#include "phxrpc/rpc.h"


SearchStub::SearchStub(phxrpc::BaseTcpStream &socket, phxrpc::ClientMonitor &client_monitor,
        phxrpc::BaseMessageHandlerFactory &msg_handler_factory)
        : socket_(socket), client_monitor_(client_monitor),
          msg_handler_factory_(msg_handler_factory) {
}

SearchStub::~SearchStub() {
}

void SearchStub::set_keep_alive(const bool keep_alive) {
    keep_alive_ = keep_alive;
}

int SearchStub::PHXEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp) {
    phxrpc::Caller caller(socket_, client_monitor_, msg_handler_factory_);
    caller.set_uri("/search/PHXEcho", -1);
    caller.set_keep_alive(keep_alive_);
    return caller.Call(req, resp);
}

int SearchStub::Search(const search::SearchRequest &req, search::SearchResult *resp) {
    phxrpc::Caller caller(socket_, client_monitor_, msg_handler_factory_);
    caller.set_uri("/search/Search", 1);
    caller.set_keep_alive(keep_alive_);
    return caller.Call(req, resp);
}

int SearchStub::Notify(const google::protobuf::StringValue &req, google::protobuf::Empty *resp) {
    phxrpc::Caller caller(socket_, client_monitor_, msg_handler_factory_);
    caller.set_uri("/search/Notify", 2);
    caller.set_keep_alive(keep_alive_);
    return caller.Call(req, resp);
}

